DROP TYPE IF EXISTS groceries;
CREATE TYPE groceries AS ENUM(
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'


);

CREATE TABLE IF NOT EXISTS shopping_list(
 shopping_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 name TEXT NOT NULL,
 price decimal(10,2) NOT NULL,
 date_added TIMESTAMP DEFAULT now() NOT NULL,
 checked BOOLEAN DEFAULT false,
 category groceries NOT NULL

)